In [2]:
import torch
v1 = torch.tensor([0,2,5]).float()
v2 = torch.tensor([2,4,7]).float()
print(v1-v1.mean())
print(v2-v2.mean())


tensor([-2.3333, -0.3333,  2.6667])
tensor([-2.3333, -0.3333,  2.6667])


In [1]:
#5: S6, Transformer, various seeds
base_cfg = {"epochs": 100}

cfg = {
    "model": "Transformer",
    "group": "SymmetricGroup",
    "group_parameter": 6,
    "frac_train" : 0.4, 
    "epochs": 1000
}

experiment_cfg = {**base_cfg, **cfg}
experiment_cfg

{'epochs': 1000,
 'model': 'Transformer',
 'group': 'SymmetricGroup',
 'group_parameter': 6,
 'frac_train': 0.4}

In [1]:
import sys
sys.path.append('../')
path = '../experiments/1L_MLP_C118/summary_metrics.json'
import json
from utils.plotting import *
summary_metrics = json.load(open(path, 'r'))
total = 0
logits = []
for key in summary_metrics.keys():
    if 'percent_x_embed' in key:
        print(key, summary_metrics[key])
        total += summary_metrics[key]
print(total)


percent_x_embed_trivial_rep 2.7415098884375766e-05
percent_x_embed_sign_rep 9.369779036205728e-06
percent_x_embed_freq_1_rep 0.14376318454742432
percent_x_embed_freq_2_rep 8.091874769888818e-05
percent_x_embed_freq_3_rep 0.0007609151070937514
percent_x_embed_freq_4_rep 1.8196147721027955e-05
percent_x_embed_freq_5_rep 0.00020351946295704693
percent_x_embed_freq_6_rep 2.604256951599382e-05
percent_x_embed_freq_7_rep 0.00038674549432471395
percent_x_embed_freq_8_rep 1.945015901583247e-05
percent_x_embed_freq_9_rep 3.0170087484293617e-05
percent_x_embed_freq_10_rep 9.817711543291807e-06
percent_x_embed_freq_11_rep 3.256629133829847e-05
percent_x_embed_freq_12_rep 0.1269906759262085
percent_x_embed_freq_13_rep 5.2154740842524916e-05
percent_x_embed_freq_14_rep 1.2422473446349613e-05
percent_x_embed_freq_15_rep 2.07438843062846e-05
percent_x_embed_freq_16_rep 3.8044854591134936e-05
percent_x_embed_freq_17_rep 0.000724479032214731
percent_x_embed_freq_18_rep 2.1049174392828718e-05
percent_x_

In [8]:
from sympy.combinatorics.named_groups import AlternatingGroup, PermutationGroup, SymmetricGroup
from sympy.combinatorics import Permutation
p1 = Permutation(0, 1, 2, 3, 4)
p2 = Permutation(1,2)(3,4)
p3 = Permutation(1, 0, 2, 3, 4)
p4 = Permutation(0,2)(3,4)
A = PermutationGroup(p1, p2)
A5_v2 = PermutationGroup(p3, p4)
A.generators
A.order()
S = SymmetricGroup(5)
A_elements = A._elements
S_elements = S._elements

#create a dict mapping each element of A to its index in S
A_to_S = {}
for i, a in enumerate(A_elements):
    for j, s in enumerate(S_elements):
        if a == s:
            A_to_S[i] = j
            break


In [9]:
len(A_elements)

60

In [10]:
A5_v2._elements

[Permutation(4),
 Permutation(4)(0, 1)(2, 3),
 Permutation(0, 2, 3, 4, 1),
 Permutation(0, 3, 1, 2, 4),
 Permutation(0, 4, 2, 1, 3),
 Permutation(1, 2, 4),
 Permutation(0, 1, 3, 2, 4),
 Permutation(0, 2, 1, 3, 4),
 Permutation(0, 3, 1, 4, 2),
 Permutation(0, 4, 3),
 Permutation(4)(1, 3, 2),
 Permutation(4)(0, 1, 2),
 Permutation(0, 2)(1, 4),
 Permutation(0, 3, 4),
 Permutation(0, 4, 2, 3, 1),
 Permutation(1, 4, 2),
 Permutation(0, 1, 4, 3, 2),
 Permutation(0, 2)(3, 4),
 Permutation(4)(0, 3, 1),
 Permutation(0, 4, 1, 2, 3),
 Permutation(2, 3, 4),
 Permutation(0, 1)(3, 4),
 Permutation(0, 2, 4, 3, 1),
 Permutation(4)(0, 3)(1, 2),
 Permutation(0, 4, 1, 3, 2),
 Permutation(4)(1, 2, 3),
 Permutation(4)(0, 1, 3),
 Permutation(0, 2, 4, 1, 3),
 Permutation(0, 3, 2, 1, 4),
 Permutation(0, 4, 2),
 Permutation(1, 3, 4),
 Permutation(0, 1, 2, 3, 4),
 Permutation(0, 2, 3, 1, 4),
 Permutation(0, 3)(2, 4),
 Permutation(0, 4, 3, 2, 1),
 Permutation(1, 4)(2, 3),
 Permutation(0, 1, 4),
 Permutation(0, 2

In [15]:
from scipy.spatial.transform import Rotation as R
a = np.sqrt(8/(5+np.sqrt(5)))
p = 2*np.pi/5

rot = R.from_rotvec(2*np.pi/5 * a*np.array([1/2, (1+np.sqrt(5))/5, 0]))
print(rot.as_matrix())

[[ 0.6685713   0.25604275  0.69817944]
 [ 0.25604275  0.80219609 -0.53937328]
 [-0.69817944  0.53937328  0.47076739]]


In [21]:
from sympy.combinatorics.homomorphisms import homomorphism
p1 = Permutation(0, 1, 2, 3, 4)
p2 = Permutation(1,2)(3,4)
p3 = Permutation(1, 0, 2, 3, 4)
p4 = Permutation(0,2)(3,4)
A = PermutationGroup(p1, p2)
A5_v2 = PermutationGroup(p3, p4)
print(A.generators)
print(A5_v2.generators)
tau = homomorphism(A, A5_v2, A.generators, A5_v2.generators)

[Permutation(0, 1, 2, 3, 4), Permutation(1, 2)(3, 4)]
[Permutation(0, 2, 3, 4, 1), Permutation(0, 2)(3, 4)]


ValueError: The given images do not define a homomorphism